# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sample Tracking Project' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sample Tracking Project
  pod 'AFNetworking', '~> 3.0'
  pod "Analytics", "3.7.0"

  target 'Sample Tracking ProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
